### ISSUE TITLE
Register to Stream

### ISSUE THREAD

**Issue by HeroHann** [DaWe35/SkyLive-GUI#11]
The restoration is not working for me. Also why is it necessary?

**Comment by DaWe35** [comment]
Hey @HeroHann, I don't understand, what is wrong?

**Comment by HeroHann** [comment]
Sorry, registration. It is not working for me and as I don't get a "key" I cannot stream.

**Comment by DaWe35** [comment]
@HeroHann You can register here: https://skylive.coolhd.hu/register
After reg, please click "Create a new stream". Is it working now? If not, what you see?
