### ISSUE TITLE
`FileNotFound` error

### ISSUE THREAD

**Issue by d4mr** [DaWe35/SkyLive-GUI#7]
![Screenshot (13)](https://user-images.githubusercontent.com/16459486/85802640-fb5bd900-b762-11ea-9cd4-3d99833ab72b.png)

**Comment by DaWe35** [comment]
@d4mr Can you please send me `stream_downloader.log` from `~/.SkyLive`?

**Comment by d4mr** [comment]
[stream_downloader.log](https://github.com/DaWe35/SkyLive-GUI/files/4840299/stream_downloader.log)
Here's the logs

**Comment by DaWe35** [comment]
Okay, I'm working on the ffmpeg issue.
